# Food-101 Dictionary: Class -> Label & Celiac Risk Assessment
food101_celiac_db = {
    "apple_pie": {"label": "Apple pie", "celiac_risk": "High", "contains_gluten": True, "notes": "Crust typically contains wheat flour."},
    "baby_back_ribs": {"label": "Baby back ribs", "celiac_risk": "Medium", "contains_gluten": None, "notes": "Meat is gluten-free, but BBQ sauces and marinades often contain wheat or soy sauce."},
    "baklava": {"label": "Baklava", "celiac_risk": "High", "contains_gluten": True, "notes": "Made with phyllo dough containing wheat."},
    "beef_carpaccio": {"label": "Beef carpaccio", "celiac_risk": "Low", "contains_gluten": False, "notes": "Raw beef, oil, and parmesan are gluten-free. Check for bread side dishes."},
    "beef_tartare": {"label": "Beef tartare", "celiac_risk": "Low", "contains_gluten": False, "notes": "Beef and raw egg are gluten-free. Caution with Worcestershire sauce or toast sides."},
    "beet_salad": {"label": "Beet salad", "celiac_risk": "Low", "contains_gluten": False, "notes": "Beets, greens, and cheese are naturally gluten-free. Check dressings."},
    "beignets": {"label": "Beignets", "celiac_risk": "High", "contains_gluten": True, "notes": "Deep-fried dough made from wheat flour."},
    "bibimbap": {"label": "Bibimbap", "celiac_risk": "High", "contains_gluten": True, "notes": "Gochujang paste almost always contains wheat. High risk from soy sauce marinades."},
    "bread_pudding": {"label": "Bread pudding", "celiac_risk": "High", "contains_gluten": True, "notes": "Main ingredient is wheat bread."},
    "breakfast_burrito": {"label": "Breakfast burrito", "celiac_risk": "High", "contains_gluten": True, "notes": "Wrapped in a wheat flour tortilla."},
    "bruschetta": {"label": "Bruschetta", "celiac_risk": "High", "contains_gluten": True, "notes": "Served on toasted wheat bread."},
    "caesar_salad": {"label": "Caesar salad", "celiac_risk": "High", "contains_gluten": True, "notes": "Contains wheat croutons; Caesar dressing often contains Worcestershire sauce."},
    "cannoli": {"label": "Cannoli", "celiac_risk": "High", "contains_gluten": True, "notes": "Fried pastry shell made from wheat flour."},
    "caprese_salad": {"label": "Caprese salad", "celiac_risk": "Low", "contains_gluten": False, "notes": "Tomatoes, mozzarella, basil, and olive oil are naturally gluten-free."},
    "carrot_cake": {"label": "Carrot cake", "celiac_risk": "High", "contains_gluten": True, "notes": "Baked with wheat flour."},
    "ceviche": {"label": "Ceviche", "celiac_risk": "Low", "contains_gluten": False, "notes": "Raw fish cured in citrus juice. Check for added soy sauce."},
    "cheesecake": {"label": "Cheesecake", "celiac_risk": "High", "contains_gluten": True, "notes": "Crust is usually made from graham crackers or wheat cookies."},
    "cheese_plate": {"label": "Cheese plate", "celiac_risk": "Medium", "contains_gluten": None, "notes": "Cheese is gluten-free, but high cross-contamination risk from crackers/bread on the plate."},
    "chicken_curry": {"label": "Chicken curry", "celiac_risk": "Medium", "contains_gluten": None, "notes": "Usually gluten-free, but some roux-based curries or thickeners use wheat flour."},
    "chicken_quesadilla": {"label": "Chicken quesadilla", "celiac_risk": "High", "contains_gluten": True, "notes": "Made with wheat flour tortillas."},
    "chicken_wings": {"label": "Chicken wings", "celiac_risk": "High", "contains_gluten": True, "notes": "Often breaded or fried in shared fryers with gluten items."},
    "chocolate_cake": {"label": "Chocolate cake", "celiac_risk": "High", "contains_gluten": True, "notes": "Baked with wheat flour."},
    "chocolate_mousse": {"label": "Chocolate mousse", "celiac_risk": "Low", "contains_gluten": False, "notes": "Chocolate, eggs, and cream are gluten-free. Verify thickeners."},
    "churros": {"label": "Churros", "celiac_risk": "High", "contains_gluten": True, "notes": "Fried dough made from wheat flour."},
    "clam_chowder": {"label": "Clam chowder", "celiac_risk": "High", "contains_gluten": True, "notes": "Thickened with wheat flour roux."},
    "club_sandwich": {"label": "Club sandwich", "celiac_risk": "High", "contains_gluten": True, "notes": "Made with sliced wheat bread."},
    "crab_cakes": {"label": "Crab cakes", "celiac_risk": "High", "contains_gluten": True, "notes": "Breadcrumbs are used as a binder."},
    "creme_brulee": {"label": "Creme brulee", "celiac_risk": "Low", "contains_gluten": False, "notes": "Custard made of egg yolks, cream, sugar, and vanilla is naturally gluten-free."},
    "croque_madame": {"label": "Croque madame", "celiac_risk": "High", "contains_gluten": True, "notes": "Made with wheat bread and béchamel sauce (wheat flour)."},
    "cup_cakes": {"label": "Cup cakes", "celiac_risk": "High", "contains_gluten": True, "notes": "Baked with wheat flour."},
    "deviled_eggs": {"label": "Deviled eggs", "celiac_risk": "Low", "contains_gluten": False, "notes": "Eggs, mayonnaise, and mustard are naturally gluten-free."},
    "donuts": {"label": "Donuts", "celiac_risk": "High", "contains_gluten": True, "notes": "Fried dough made from wheat flour."},
    "dumplings": {"label": "Dumplings", "celiac_risk": "High", "contains_gluten": True, "notes": "Wrapper is made from wheat flour."},
    "edamame": {"label": "Edamame", "celiac_risk": "Low", "contains_gluten": False, "notes": "Steamed soybeans are naturally gluten-free. Avoid soy sauce seasoning."},
    "eggs_benedict": {"label": "Eggs benedict", "celiac_risk": "High", "contains_gluten": True, "notes": "Served on an English muffin (wheat flour)."},
    "escargots": {"label": "Escargots", "celiac_risk": "Low", "contains_gluten": False, "notes": "Snails and garlic butter are gluten-free. Avoid side bread."},
    "falafel": {"label": "Falafel", "celiac_risk": "Medium", "contains_gluten": None, "notes": "Chickpea-based, but wheat flour is often added as a binder; high shared-fryer risk."},
    "filet_mignon": {"label": "Filet mignon", "celiac_risk": "Low", "contains_gluten": False, "notes": "Plain meat is gluten-free. Verify accompanying sauces."},
    "fish_and_chips": {"label": "Fish and chips", "celiac_risk": "High", "contains_gluten": True, "notes": "Fish is coated in beer batter made with wheat flour."},
    "foie_gras": {"label": "Foie gras", "celiac_risk": "Low", "contains_gluten": False, "notes": "Duck/goose liver is gluten-free. Often served with brioche (avoid)."},
    "french_fries": {"label": "French fries", "celiac_risk": "Medium", "contains_gluten": None, "notes": "Potatoes are gluten-free, but cross-contamination in shared fryers is very common."},
    "french_onion_soup": {"label": "French onion soup", "celiac_risk": "High", "contains_gluten": True, "notes": "Topped with toasted wheat bread and broth is often thickened with flour."},
    "french_toast": {"label": "French toast", "celiac_risk": "High", "contains_gluten": True, "notes": "Made by soaking wheat bread in egg batter."},
    "fried_calamari": {"label": "Fried calamari", "celiac_risk": "High", "contains_gluten": True, "notes": "Breaded with wheat flour before frying."},
    "fried_rice": {"label": "Fried rice", "celiac_risk": "High", "contains_gluten": True, "notes": "Seasoned with standard soy sauce (contains wheat)."},
    "frozen_yogurt": {"label": "Frozen yogurt", "celiac_risk": "Low", "contains_gluten": False, "notes": "Base is generally gluten-free. Watch out for cookie/granola toppings."},
    "garlic_bread": {"label": "Garlic bread", "celiac_risk": "High", "contains_gluten": True, "notes": "Made from wheat bread."},
    "gnocchi": {"label": "Gnocchi", "celiac_risk": "High", "contains_gluten": True, "notes": "Potato dough is traditionally bound with wheat flour."},
    "greek_salad": {"label": "Greek salad", "celiac_risk": "Low", "contains_gluten": False, "notes": "Cucumbers, tomatoes, olives, and feta cheese are naturally gluten-free."},
    "grilled_cheese_sandwich": {"label": "Grilled cheese sandwich", "celiac_risk": "High", "contains_gluten": True, "notes": "Made with wheat bread."},
    "grilled_salmon": {"label": "Grilled salmon", "celiac_risk": "Low", "contains_gluten": False, "notes": "Plain fish is gluten-free. Check marinades for soy sauce."},
    "guacamole": {"label": "Guacamole", "celiac_risk": "Low", "contains_gluten": False, "notes": "Avocados, lime, and seasonings are gluten-free. Pair with corn tortilla chips."},
    "gyoza": {"label": "Gyoza", "celiac_risk": "High", "contains_gluten": True, "notes": "Wrapper is made from wheat flour."},
    "hamburger": {"label": "Hamburger", "celiac_risk": "High", "contains_gluten": True, "notes": "Served in a wheat flour bun."},
    "hot_and_sour_soup": {"label": "Hot and sour soup", "celiac_risk": "High", "contains_gluten": True, "notes": "Contains soy sauce and is thickened with starch/flour."},
    "hot_dog": {"label": "Hot dog", "celiac_risk": "High", "contains_gluten": True, "notes": "Served in a wheat flour bun."},
    "huevos_rancheros": {"label": "Huevos rancheros", "celiac_risk": "Medium", "contains_gluten": None, "notes": "Gluten-free if made with corn tortillas, high risk if flour tortillas are used."},
    "hummus": {"label": "Hummus", "celiac_risk": "Low", "contains_gluten": False, "notes": "Chickpeas and tahini are gluten-free. Avoid pita bread sides."},
    "ice_cream": {"label": "Ice cream", "celiac_risk": "Low", "contains_gluten": False, "notes": "Plain ice cream is gluten-free. Avoid cookie dough, brownie mix-ins, or cones."},
    "lasagna": {"label": "Lasagna", "celiac_risk": "High", "contains_gluten": True, "notes": "Pasta sheets contain wheat flour; béchamel sauce uses wheat flour."},
    "lobster_bisque": {"label": "Lobster bisque", "celiac_risk": "High", "contains_gluten": True, "notes": "Thickened with wheat flour roux."},
    "lobster_roll_sandwich": {"label": "Lobster roll sandwich", "celiac_risk": "High", "contains_gluten": True, "notes": "Served in a toasted wheat bun."},
    "macaroni_and_cheese": {"label": "Macaroni and cheese", "celiac_risk": "High", "contains_gluten": True, "notes": "Wheat pasta with a cheese sauce thickened with flour."},
    "macarons": {"label": "Macarons", "celiac_risk": "Low", "contains_gluten": False, "notes": "Traditionally made with almond flour, egg whites, and sugar."},
    "miso_soup": {"label": "Miso soup", "celiac_risk": "Medium", "contains_gluten": None, "notes": "Miso paste can be fermented with barley or wheat (read labels carefully)."},
    "mussels": {"label": "Mussels", "celiac_risk": "Low", "contains_gluten": False, "notes": "Mussels and white wine broth are gluten-free. Do not eat with accompanying bread."},
    "nachos": {"label": "Nachos", "celiac_risk": "Medium", "contains_gluten": None, "notes": "Corn tortilla chips are gluten-free, but check cheese sauces and fryer contamination."},
    "omelette": {"label": "Omelette", "celiac_risk": "Low", "contains_gluten": False, "notes": "Eggs, cheese, and vegetables are naturally gluten-free."},
    "onion_rings": {"label": "Onion rings", "celiac_risk": "High", "contains_gluten": True, "notes": "Coated in wheat flour batter/breadcrumbs and deep-fried."},
    "oysters": {"label": "Oysters", "celiac_risk": "Low", "contains_gluten": False, "notes": "Raw oysters are gluten-free. Avoid fried or Rockefeller preparations."},
    "pad_thai": {"label": "Pad thai", "celiac_risk": "Medium", "contains_gluten": None, "notes": "Uses rice noodles, but sauces may contain wheat-derived soy sauce."},
    "paella": {"label": "Paella", "celiac_risk": "Low", "contains_gluten": False, "notes": "Rice, seafood, meat, and spices are naturally gluten-free."},
    "pancakes": {"label": "Pancakes", "celiac_risk": "High", "contains_gluten": True, "notes": "Batter is made from wheat flour."},
    "panna_cotta": {"label": "Panna cotta", "celiac_risk": "Low", "contains_gluten": False, "notes": "Gelatin-based dessert, naturally gluten-free."},
    "peking_duck": {"label": "Peking duck", "celiac_risk": "High", "contains_gluten": True, "notes": "Served with hoisin sauce and wheat flour pancakes."},
    "pho": {"label": "Pho", "celiac_risk": "Low", "contains_gluten": False, "notes": "Made with rice noodles and broth. Avoid hoisin sauce topping."},
    "pizza": {"label": "Pizza", "celiac_risk": "High", "contains_gluten": True, "notes": "Traditional crust is made from wheat flour."},
    "pork_chop": {"label": "Pork chop", "celiac_risk": "Low", "contains_gluten": False, "notes": "Plain meat is gluten-free. Check gravies or breadings."},
    "poutine": {"label": "Poutine", "celiac_risk": "High", "contains_gluten": True, "notes": "Gravy is almost always thickened with wheat flour; shared fryer risk for fries."},
    "prime_rib": {"label": "Prime rib", "celiac_risk": "Low", "contains_gluten": False, "notes": "Meat is gluten-free. Ensure au jus is not thickened with flour."},
    "pulled_pork_sandwich": {"label": "Pulled pork sandwich", "celiac_risk": "High", "contains_gluten": True, "notes": "Served in a wheat bun; BBQ sauce may contain gluten."},
    "ramen": {"label": "Ramen", "celiac_risk": "High", "contains_gluten": True, "notes": "Ramen noodles are made of wheat flour; broth contains soy sauce."},
    "ravioli": {"label": "Ravioli", "celiac_risk": "High", "contains_gluten": True, "notes": "Pasta dough is made from wheat flour."},
    "red_velvet_cake": {"label": "Red velvet cake", "celiac_risk": "High", "contains_gluten": True, "notes": "Baked with wheat flour."},
    "risotto": {"label": "Risotto", "celiac_risk": "Low", "contains_gluten": False, "notes": "Arborio rice base is naturally gluten-free. Verify stock ingredients."},
    "samosa": {"label": "Samosa", "celiac_risk": "High", "contains_gluten": True, "notes": "Pastry shell is made from wheat flour."},
    "sashimi": {"label": "Sashimi", "celiac_risk": "Low", "contains_gluten": False, "notes": "Raw sliced fish is naturally gluten-free. Use gluten-free tamari instead of soy sauce."},
    "scallops": {"label": "Scallops", "celiac_risk": "Low", "contains_gluten": False, "notes": "Scallops are gluten-free. Ensure they aren't dusted with flour before searing."},
    "seaweed_salad": {"label": "Seaweed salad", "celiac_risk": "High", "contains_gluten": True, "notes": "Pre-made seaweed salad dressing almost always contains wheat soy sauce."},
    "shrimp_and_grits": {"label": "Shrimp and grits", "celiac_risk": "Low", "contains_gluten": False, "notes": "Grits (cornmeal) and shrimp are naturally gluten-free."},
    "spaghetti_bolognese": {"label": "Spaghetti bolognese", "celiac_risk": "High", "contains_gluten": True, "notes": "Made with wheat pasta."},
    "spaghetti_carbonara": {"label": "Spaghetti carbonara", "celiac_risk": "High", "contains_gluten": True, "notes": "Made with wheat pasta."},
    "spring_rolls": {"label": "Spring rolls", "celiac_risk": "High", "contains_gluten": True, "notes": "Wrappers are made from wheat flour."},
    "steak": {"label": "Steak", "celiac_risk": "Low", "contains_gluten": False, "notes": "Plain grilled meat is naturally gluten-free."},
    "strawberry_shortcake": {"label": "Strawberry shortcake", "celiac_risk": "High", "contains_gluten": True, "notes": "Shortcake or biscuit base is baked with wheat flour."},
    "sushi": {"label": "Sushi", "celiac_risk": "Medium", "contains_gluten": None, "notes": "Rice and fish are safe, but imitation crab (surimi), soy sauce, and tempura contain gluten."},
    "tacos": {"label": "Tacos", "celiac_risk": "Low", "contains_gluten": False, "notes": "Traditional corn tacos are gluten-free. Avoid wheat tortillas and spiced meat fillers with flour."},
    "takoyaki": {"label": "Takoyaki", "celiac_risk": "High", "contains_gluten": True, "notes": "Octopus balls made from a wheat flour batter."},
    "tiramisu": {"label": "Tiramisu", "celiac_risk": "High", "contains_gluten": True, "notes": "Contains ladyfinger biscuits made of wheat flour."},
    "tuna_tartare": {"label": "Tuna tartare", "celiac_risk": "Medium", "contains_gluten": None, "notes": "Tuna is gluten-free, but marinades frequently contain soy sauce."},
    "waffles": {"label": "Waffles", "celiac_risk": "High", "contains_gluten": True, "notes": "Made from wheat flour batter."}
}


def get_dish_assessment(predicted_class: str) -> dict:
    """
    Return risk info for a predicted class, with a safe fallback.
    This returns a dict because API needs JSON format.
    """
    return food101_celiac_db.get(
        predicted_class,
        {
            "label": predicted_class,
            "celiac_risk": "Unknown",
            "contains_gluten": None,
            "notes": "No data available for this class."
            },
    )
